<RootLayout>:

    MDBoxLayout:

        orientation: "vertical"
        width: root.width
        height: root.height

        MDBoxLayout:
            id: header_container
            size_hint_y: None

        Screen:
            canvas.before:
                Color:
                    rgba: 8, 8, 0, .4
                Rectangle:
                    pos: self.pos
                    size: self.size
            id: page_container
